export const days = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday'
];
export const months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December'
];
export const places = [
  {
    id: 1,
    name: 'Tokyo',
    near: 'Tokyo, JP',
    lat: 35.6828387,
    lon: 139.7594549,
    currentWeatherData: {},
    fiveDaysWeatherData: {},
  },
  {
    id: 2,
    name: 'Yokohama',
    near: 'Yokohama, JP',
    lat: 35.444991,
    lon: 139.636768,
    currentWeatherData: {},
    fiveDaysWeatherData: {},
  },
  {
    id: 3,
    name: 'Kyoto',
    near: 'Kyoto, JP',
    lat: 35.021041,
    lon: 135.7556075,
    currentWeatherData: {},
    fiveDaysWeatherData: {},
  },
  {
    id: 4,
    name: 'Osaka',
    near: 'Osaka, JP',
    lat: 34.6937569,
    lon: 135.5014539,
    currentWeatherData: {},
    fiveDaysWeatherData: {},
  },
  {
    id: 5,
    name: 'Sapporo',
    near: 'Sapporo, JP',
    lat: 43.061936,
    lon: 141.3542924,
    currentWeatherData: {},
    fiveDaysWeatherData: {},
  },
  {
    id: 6,
    name: 'Nagoya',
    near: 'Nagoya, JP',
    lat: 35.1851045,
    lon: 136.8998438,
    currentWeatherData: {},
    fiveDaysWeatherData: {},
  },
];
